project:
  type: manuscript

execute:
  freeze: auto

format:
  html:
    toc: true
    embed-resources: true
    comments:
      hypothesis: true
  docx: default
  jats: default
  agu-pdf: default

resources:
  - notebooks
  - assets

