project:
  type: manuscript
  output-dir: _manuscript

execute:
  freeze: auto
  preview: false

format:
  html:
    toc: true
    embed-resources: true
    comments:
      hypothesis: true
    preview: true
  agu-pdf:
    preview: true
  docx: default
  jats: default

resources:
  - notebooks
  - assets

chapters:
  - notebooks/data_clean.ipynb
  - notebooks/data_collect.ipynb
  - notebooks/propensity_scores.ipynb
  - notebooks/manufactured_vars.ipynb